"""Added three new fields in the User model

Revision ID: 3e5cf34633bf
Revises: caac1b5be67f
Create Date: 2022-05-25 20:04:49.043558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e5cf34633bf'
down_revision = 'caac1b5be67f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('category', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'created_at')
    op.drop_column('user', 'category')
    op.drop_column('user', 'role')
    # ### end Alembic commands ###
