"""add desc. column in category table

Revision ID: 40e309d29ed7
Revises: cf8ff3e0b56a
Create Date: 2022-10-16 17:40:40.340972

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40e309d29ed7'
down_revision = 'cf8ff3e0b56a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('description', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('category', 'description')
    # ### end Alembic commands ###
