"""Added some attrs. in organization data model

Revision ID: 727174f9fb1d
Revises: b4a2fe3f626e
Create Date: 2022-12-13 12:27:22.494564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '727174f9fb1d'
down_revision = 'b4a2fe3f626e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organization', sa.Column('logo_url', sa.String(length=128), nullable=True))
    op.add_column('organization', sa.Column('phone', sa.String(length=32), nullable=False))
    op.add_column('organization', sa.Column('website_url', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organization', 'website_url')
    op.drop_column('organization', 'phone')
    op.drop_column('organization', 'logo_url')
    # ### end Alembic commands ###
