"""added type field to Space

Revision ID: 83c599d99395
Revises: c343137cb1a3
Create Date: 2024-03-10 15:11:17.112970

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c599d99395'
down_revision = 'c343137cb1a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('space', sa.Column('type', sa.Enum('undefined', 'coworking', 'residency', 'workshop_studio', 'performance_space', name='spacetype'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('space', 'type')
    # ### end Alembic commands ###
