"""add_space_tool_rel

Revision ID: 84b334b2c5ea
Revises: bf6b8be3201e
Create Date: 2022-07-13 19:47:12.708632

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84b334b2c5ea'
down_revision = 'bf6b8be3201e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('space_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tool', 'space', ['space_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tool', type_='foreignkey')
    op.drop_column('tool', 'space_id')
    # ### end Alembic commands ###
