"""empty message

Revision ID: 95a7709aae1c
Revises: 
Create Date: 2022-10-26 17:03:17.976651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '95a7709aae1c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('organization',
    # sa.Column('id', sa.Integer(), nullable=False),
    # sa.Column('name', sa.String(length=80), nullable=False),
    # sa.Column('description', sa.String(length=1024), nullable=False),
    # sa.Column('address', sa.String(length=200), nullable=True),
    # sa.Column('category_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    # sa.PrimaryKeyConstraint('id'),
    # sa.UniqueConstraint('name')
    # )
    # op.create_table('reservation_tool',
    # sa.Column('reservation_id', sa.Integer(), nullable=True),
    # sa.Column('tool_id', sa.Integer(), nullable=True),
    # sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], ),
    # sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], )
    # )
    # op.add_column('category', sa.Column('description', sa.String(length=128), nullable=True))
    # op.add_column('category', sa.Column('is_organization', sa.Boolean(), nullable=False))
    # op.create_foreign_key(None, 'interval', 'reservation', ['reservation_id'], ['id'], ondelete='CASCADE')
    # op.create_foreign_key(None, 'interval', 'calendar', ['calendar_id'], ['id'], ondelete='CASCADE')
    op.add_column('reservation', sa.Column('description', sa.String(length=1024), nullable=False))
    op.add_column('reservation', sa.Column('attendance_num', sa.Integer(), nullable=True))
    op.add_column('reservation', sa.Column('min_age', sa.Integer(), nullable=True))
    op.add_column('reservation', sa.Column('max_age', sa.Integer(), nullable=True))
    op.alter_column('space', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('space', 'capacity',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('tool', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.add_column('user', sa.Column('gender', sa.Enum('male', 'female', 'prefer_not_answer', name='gender'), nullable=True))
    op.add_column('user', sa.Column('phone', sa.String(length=50), nullable=False))
    op.add_column('user', sa.Column('birthday', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('activated', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('website_url', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('avatar_url', sa.String(length=120), nullable=True))
    op.add_column('user', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('organization_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'organization', ['organization_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'organization_id')
    op.drop_column('user', 'address')
    op.drop_column('user', 'avatar_url')
    op.drop_column('user', 'website_url')
    op.drop_column('user', 'activated')
    op.drop_column('user', 'birthday')
    op.drop_column('user', 'phone')
    op.drop_column('user', 'gender')
    op.alter_column('tool', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.alter_column('space', 'capacity',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('space', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.drop_column('reservation', 'max_age')
    op.drop_column('reservation', 'min_age')
    op.drop_column('reservation', 'attendance_num')
    op.drop_column('reservation', 'description')
    op.drop_constraint(None, 'interval', type_='foreignkey')
    op.drop_constraint(None, 'interval', type_='foreignkey')
    op.drop_column('category', 'is_organization')
    op.drop_column('category', 'description')
    op.drop_table('reservation_tool')
    op.drop_table('organization')
    # ### end Alembic commands ###
