"""added deleted_at to User

Revision ID: af0764db79b5
Revises: 83c599d99395
Create Date: 2024-04-18 16:54:02.007096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af0764db79b5'
down_revision = '83c599d99395'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'deleted_at')
    # ### end Alembic commands ###
