"""AddedRelationships

Revision ID: af9b427e2445
Revises: cc9b55f92db5
Create Date: 2022-07-30 19:10:08.068907

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'af9b427e2445'
down_revision = 'cc9b55f92db5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reservation_calendar',
    sa.Column('reservation_id', sa.Integer(), nullable=True),
    sa.Column('calendar_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['calendar_id'], ['calendar.id'], ),
    sa.ForeignKeyConstraint(['reservation_id'], ['reservation.id'], )
    )
    op.add_column('interval', sa.Column('reservation_id', sa.Integer(), nullable=True))
    op.drop_constraint('interval_ibfk_1', 'interval', type_='foreignkey')
    op.create_foreign_key(None, 'interval', 'calendar', ['calendar_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'interval', 'reservation', ['reservation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('reservation_ibfk_4', 'reservation', type_='foreignkey')
    op.drop_column('reservation', 'calendar_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('calendar_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key('reservation_ibfk_4', 'reservation', 'calendar', ['calendar_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'interval', type_='foreignkey')
    op.drop_constraint(None, 'interval', type_='foreignkey')
    op.create_foreign_key('interval_ibfk_1', 'interval', 'calendar', ['calendar_id'], ['id'])
    op.drop_column('interval', 'reservation_id')
    op.drop_table('reservation_calendar')
    # ### end Alembic commands ###
