"""Rename count to quantity

Revision ID: b4a2fe3f626e
Revises: 95a7709aae1c
Create Date: 2022-11-10 04:37:15.125480

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b4a2fe3f626e'
down_revision = '95a7709aae1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('space', 'cover_img_url')
    op.drop_column('space', 'price')
    op.add_column('tool', sa.Column('quantity', sa.Integer(), nullable=True))
    op.drop_column('tool', 'cover_img_url')
    op.drop_column('tool', 'price')
    op.drop_column('tool', 'count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tool', sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('tool', sa.Column('price', mysql.FLOAT(), nullable=False))
    op.add_column('tool', sa.Column('cover_img_url', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    op.drop_column('tool', 'quantity')
    op.add_column('space', sa.Column('price', mysql.FLOAT(), nullable=False))
    op.add_column('space', sa.Column('cover_img_url', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
