"""add_tool_model

Revision ID: bf6b8be3201e
Revises: fac249d6d092
Create Date: 2022-07-13 17:20:42.912001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf6b8be3201e'
down_revision = 'fac249d6d092'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=128), nullable=False),
    sa.Column('guidelines', sa.String(length=256), nullable=False),
    sa.Column('has_operator', sa.Boolean(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('image', sa.Column('tool_id', sa.Integer(), nullable=True))
    op.alter_column('image', 'space_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(None, 'image', 'tool', ['tool_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'image', type_='foreignkey')
    op.alter_column('image', 'space_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('image', 'tool_id')
    op.drop_table('tool')
    # ### end Alembic commands ###
