"""Added discount field to Reservation

Revision ID: c343137cb1a3
Revises: 325259432dfa
Create Date: 2023-03-15 09:59:15.935230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c343137cb1a3'
down_revision = '325259432dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('reservation', sa.Column('discount', sa.Float(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reservation', 'discount')
    # ### end Alembic commands ###
