"""Added category_space and category_tool m2m relations

Revision ID: ca5209edcc67
Revises: af9b427e2445
Create Date: 2022-10-11 17:32:44.027543

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ca5209edcc67'
down_revision = 'af9b427e2445'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Enum('hour', 'day', name='unit'), nullable=True),
    sa.Column('unit_value', sa.Float(), nullable=True),
    sa.Column('price_unit', sa.Enum('egp', 'usd', name='priceunit'), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['space.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'space_id', 'unit', 'unit_value')
    )
    op.create_table('category_tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Enum('hour', 'day', 'gram', name='toolunit'), nullable=True),
    sa.Column('unit_value', sa.Float(), nullable=True),
    sa.Column('price_unit', sa.Enum('egp', 'usd', name='priceunit'), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'tool_id', 'unit', 'unit_value')
    )
    op.add_column('space', sa.Column('capacity', sa.Integer(), nullable=True))
    op.alter_column('space', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    op.add_column('tool', sa.Column('count', sa.Integer(), nullable=True))
    op.alter_column('tool', 'price',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tool', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.drop_column('tool', 'count')
    op.alter_column('space', 'price',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.drop_column('space', 'capacity')
    op.drop_table('category_tool')
    op.drop_table('category_space')
    # ### end Alembic commands ###
