"""init db

Revision ID: cf8ff3e0b56a
Revises: 
Create Date: 2022-10-16 17:07:16.279341

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf8ff3e0b56a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_space',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('space_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Enum('hour', 'day', name='unit'), nullable=True),
    sa.Column('unit_value', sa.Float(), nullable=True),
    sa.Column('price_unit', sa.Enum('egp', 'usd', name='priceunit'), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['space_id'], ['space.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'space_id', 'unit', 'unit_value')
    )
    op.create_table('category_tool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('tool_id', sa.Integer(), nullable=False),
    sa.Column('unit', sa.Enum('hour', 'day', 'gram', name='toolunit'), nullable=True),
    sa.Column('unit_value', sa.Float(), nullable=True),
    sa.Column('price_unit', sa.Enum('egp', 'usd', name='priceunit'), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tool.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_id', 'tool_id', 'unit', 'unit_value')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('category_tool')
    op.drop_table('category_space')
    # ### end Alembic commands ###
